<?php
/** @var Member $block */
use Diller\LoyaltyProgram\Block\Frontend\Member;

/** @var $escaper \Magento\Framework\Escaper */

$loyaltyHelper = $this->helper('Diller\LoyaltyProgram\Helper\Data');

// member details
$is_member = false;
if($customer = $block->getCustomer()){
    $valid_stamp_cards = $stamp_cards = [];
    $member = $loyaltyHelper->searchMemberByCustomerId($customer->getId());
    if($member){
        $is_member = $member->getConsent()->getGdprAccepted();
    }
    if($is_member && $stamp_cards = $block->getMemberStampCards($member['id'])){
        foreach ($stamp_cards as $stamp_card) {
            $price_rule = $loyaltyHelper->getPriceRule($stamp_card->getExternalId(), "Stamp Card - " . $stamp_card->getTitle());
            if(!$price_rule) continue;

            $stamp_card_products = [];
            foreach ($price_rule->getActionCondition()->getConditions() as $price_rule_conditions){
                foreach(explode(',', $price_rule_conditions->getValue()) as $product_sku){
                    if($product_found = $loyaltyHelper->getMagentoProduct('', $product_sku)){
                        $stamp_card_products[] = $product_found;
                    }
                }
            }
            $stamp_card['products'] = $stamp_card_products;
            if(!empty($stamp_card_products)) $valid_stamp_cards[] = $stamp_card;
        }
    }
}

// store details
$loyaltyDetails = $loyaltyHelper->getLoyaltyDetails();
?>
<?php if($loyaltyDetails) { ?>
    <?php if($is_member) { ?>
        <div class="diller-container stamp-cards">
            <h2 class="page-title">
                <span id="diller-stamp-cards-container-title-cart" style="display:none" class="base" data-ui-id="page-title-wrapper"><b><?= $loyaltyDetails['storeName'] ?></b> <?= $escaper->escapeHtml(__('stamp cards')) ?></span>
                <span id="diller-stamp-cards-container-title-loyalty-page" class="base" data-ui-id="page-title-wrapper" style="text-transform: capitalize"><?= $escaper->escapeHtml(__('stamp cards')) ?></span>
            </h2>
            <hr>

            <?php if(!empty($valid_stamp_cards)) { ?>
                <div class="stamp-cards-container">
                    <?php foreach ($valid_stamp_cards as $stamp_card) { ?>
                        <div class="stamp-card id_<?= $stamp_card->getId() ?>">
                            <h3><?= $stamp_card->getTitle() ?></h3>
                            <p><?= $stamp_card->getDescription() ?> (<?=$stamp_card->getStampsCollected() ?>/<?=$stamp_card->getRequiredStamps() ?>)</p>
                            <div class="stamps">
                                <?php for ($x = 1; $x <= $stamp_card->getRequiredStamps(); $x++) { ?>
                                    <div class="stamp <?= $stamp_card->getStampsCollected() >= $x ? 'collected' : '' ?>" <?= $x == $stamp_card->getRequiredStamps() ? 'title="'.$stamp_card->getLastStampText().'"' : '' ?>></div>
                                <?php } ?>
                            </div>
                            <div class="products">
                                <?php if($stamp_card->getRequiredPoints() > 0){
                                    echo "<p class='required_points'>" . sprintf($escaper->escapeHtml(__("%s points needed to add a stamp to this card")), $stamp_card->getRequiredPoints()) . "</p>";
                                } ?>
                                <p>
                                    <?= $escaper->escapeHtml(__('To add a new stamp to this card')) ?>,
                                    <?= count($stamp_card['products']) > 1 ? $escaper->escapeHtml(__('you must buy one of following products')) : $escaper->escapeHtml(__('you must buy the following product')) ?>:
                                </p>
                                <ul>
                                    <?php foreach($stamp_card['products'] as $product){ ?>
                                        <li><a href="<?= $product->getProductUrl() ?>" target="_blank"><?= $product->getName() ?></a></li>
                                    <?php } ?>
                                </ul>
                            </div>
                            <style>
                                .stamp-cards .id_<?= $stamp_card->getId() ?> .stamp{
                                    background-image: url("<?= $stamp_card->getImageUrl() ?>") !important;
                                }
                            </style>
                        </div>
                    <?php } ?>
                </div>
            <?php } else { ?>
                <p><?= $escaper->escapeHtml(__('No stamp cards found')) ?></p>
            <?php } ?>
        </div>
        <style>
            body.checkout-cart-index span#diller-stamp-cards-container-title-cart{
                display: block !important;
            }
            body.checkout-cart-index #diller-stamp-cards-container-title-loyalty-page{
                display: none;
            }
            .diller-container.stamp-cards{
                float:left;
                width: 100%;
            }
            p.required_points {
                margin: 10px 0 !important;
                font-size: 14px;
                padding: 0 0 0 24px;
            }
            p.required_points:before {
                background-image: url(https://magento.prerelease.dillerapp.com/static/version1695714213/frontend/Magento/luma/en_GB/Diller_LoyaltyProgram/img/info.svg);
                background-position: center center;
                background-repeat: no-repeat;
                background-size: contain;
                margin: 3px 0 0 -24px;
                position: relative;
                height: 16px;
                content: "";
                width: 16px;
                float: left;
            }
            .stamp-cards-container {
                display: flex;
                flex-wrap: wrap;
                gap: 24px;
            }
            .stamp-cards-container > div {
                flex: 0 calc(50% - 62px);
                background-color: whitesmoke;
                padding: 25px;
                margin: 0;
            }

            .stamp-card {
                margin: 0 0 40px;
                float: left;
                width: 100%;
            }
            .stamp-card h3 {
                text-transform: capitalize;
                margin: 0 0 5px;
            }
            .stamp-card p {
                margin: 0 0 15px;
            }
            .stamp-card .stamps {
                flex-wrap: wrap;
                display: flex;
                gap: 19px;
            }
            .stamp-card .stamps .price{
                justify-content: center;
                align-items: center;
                width: min-content;
                font-weight: 600;
                min-width: 80px;
                display: flex;
            }
            .stamp-card .stamps .stamp {
                background-position: center center;
                background-repeat: no-repeat;
                border: 3px solid #f5f5f5;
                background-color: #fff;
                background-size: 60%;
                border-radius: 100%;
                display: flex;
                height: 60px;
                opacity: 0.5;
                width: 60px;
            }
            .stamp-card .stamps .stamp.collected {
                border-color: #90b3c7;
                opacity: 1;
            }
            .stamp-card .products{
                margin:20px 0 0 0;
            }
            .stamp-card .products ul{
                list-style: initial;
                padding: 0 0 0 30px;
                display: inline-grid;
                margin:0;
            }
            .stamp-card .products ul li{
                margin: 0 0 5px;
            }
            .stamp-card .products ul li:last-child{
                margin: 0;
            }
            body.checkout-cart-index span#diller-stamp-cards-container-title-cart {
                font-size: 20px;
            }
            @media (max-width: 800px){
                body.checkout-cart-index .diller-container.stamp-cards{
                    margin:15px 0;
                }
                body.checkout-cart-index .diller-container.stamp-cards h2, body.checkout-cart-index .diller-container.stamp-cards .stamp-cards-container {
                    padding: 0 15px;
                }

                .stamp-cards-container > div {
                    flex: 0 100% !important;
                    padding: 20px !important;
                }
                .stamp-card .stamps {
                    gap: 10px;
                }
                .stamp-card .stamps .stamp {
                    width: 50px;
                    height: 50px;
                }
            }
        </style>
    <?php } ?>
<?php } ?>