<?php
/** @var Member $block */
use Diller\LoyaltyProgram\Block\Frontend\Member;

$loyaltyHelper = $this->helper('Diller\LoyaltyProgram\Helper\Data');

// member details
$is_member = false;
if($customer = $block->getCustomer()){
    $is_member = ($member = $loyaltyHelper->searchMemberByCustomerId($customer->getId()));
    if($is_member) $coupons = $block->getMemberCoupons($member['id']);
}

// store details
$loyaltyDetails = $loyaltyHelper->getLoyaltyDetails();
?>
<?php if($is_member && $loyaltyDetails['pointsSystem']['enabled']) { ?>
    <div class="diller-container coupons">
        <h3 class="page-title">
            <span class="base" data-ui-id="page-title-wrapper"><b><?= $loyaltyDetails['storeName'] ?></b> discount codes</span>
        </h3>
        <hr>
        <?php echo $this->getLayout()->createBlock("Diller\LoyaltyProgram\Block\Frontend\Member")->setTemplate("Diller_LoyaltyProgram::coupons.phtml")->toHtml() ?>
    </div>


    <style>
        .cart-discount .diller-container.coupons{
            float:left;
            width: 100%;
        }
        .diller-coupon {
            line-height: normal;
            background-color: #f5f5f5;
        }

        .diller-coupon-container {
            margin-bottom: 30px;
            overflow-x: auto;
            display: flex;
            gap: 4%;
            flex-wrap: wrap;
        }

        .diller-coupon-container::-webkit-scrollbar {
            height: 10px;
        }

        .diller-coupon-container::-webkit-scrollbar-thumb {
            background-color: #c1c1c1;
            border-radius: 10px;
        }

        .diller-coupon-container .diller-coupon {
            flex: 0 0 22%;
            text-align: center;
            margin-bottom: 35px;
            background-color: #ebebeb;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
        }

        .diller-coupon-container .diller-coupon--grayout {
            position: relative;
        }

        .diller-coupon-container .diller-coupon--grayout::before {
            content: "";
            position: absolute;
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
            opacity: 0.75;
            background-color: #ebebeb;
        }

        .diller-coupon-container .diller-coupon--grayout .diller-button {
            position: relative;
        }

        .diller-coupon-inner {
            padding: 20px;
            border-bottom: 2px dashed #d3d3d3d4;
        }

        .diller-coupon-inner-bottom {
            padding: 20px;
        }

        .diller-coupon-name {
            text-align: center;
            margin: 15px 0;
            font-weight: bolder;
            font-size: 1.5rem;
            word-break: break-word;
        }

        .diller-coupon-promo-code {
            margin-top: 20px;
        }

        .diller-coupon-img {
            text-align: center;
            min-height: 100px;
            background-size: contain;
            background-position-x: center;
            background-repeat: no-repeat;
        }

        .diller-coupon-img > img {
            display: inline-block !important;
        }

        .diller-coupon-img[style*=\.svg] {
            min-height: 50px;
        }

        .diller-coupon-usage {
            font-size: var(--global--font-size-base);
            margin: 0;
        }

        .diller-coupon-discount {
            margin: 20px 0;
        }

        .diller-coupon-points {
            padding: 15px;
            font-weight: bold;
        }

        .diller-coupon-bottom {
            display: flex;
            justify-content: center;
        }

        .diller-coupon-code {
            background-color: #dadada;
            width: 100%;
            padding: 15px;
            text-align: center;
        }

        .diller-coupon-code__label {
            margin-bottom: 10px;
        }

        .diller-coupon-code__text {
            font-weight: bold;
            text-transform: uppercase;
        }

        .diller-coupon--single {
            flex: 0 0 33%;
            padding: 0 !important;
        }

        .diller-coupon--single .diller-coupon-inner {
            border-bottom: 0;
        }

        .diller-coupon--single .diller-coupon-name {
            font-size: 2rem;
        }

        .diller-coupon--single .diller-coupon-img {
            min-height: 200px;
        }

        .diller-coupon--single .diller-coupon-img[style*=\.svg] {
            min-height: 100px;
            margin-top: 20px;
        }

        .diller-coupon--single .diller-coupon-description {
            margin-bottom: 20px;
        }

        .diller-coupon--single .diller-coupon-usage {
            font-style: italic;
            margin-top: 20px;
        }

        .diller-coupon--single .diller-coupon-points {
            font-weight: bold;
        }

        .diller-coupon--single .diller-coupon-points-expiration {
            margin: 20px 0;
            font-style: italic;
        }

        .diller-coupon--single .diller-coupon-bottom {
            flex-flow: column;
            margin-bottom: 0;
        }

        .diller-coupon--single .diller-coupon-bottom .diller-coupon-code {
            padding: 15px;
        }

        .diller-coupon--single .diller-coupon-win-text {
            font-weight: bold;
            text-transform: uppercase;
        }
    </style>
<?php } ?>
