<?php
    /** @var Member $block */
    use Diller\LoyaltyProgram\Block\Frontend\Member;

    $loyaltyHelper = $this->helper('Diller\LoyaltyProgram\Helper\Data');

    // member details
    $is_member = false;
    if($customer = $block->getCustomer()){
        $is_member = ($member = $loyaltyHelper->searchMemberByCustomerId($customer->getId()));
        if($is_member) $coupons = $block->getMemberCoupons($member['id']);
    }

    // store details
    $loyaltyDetails = $loyaltyHelper->getLoyaltyDetails();
?>
<?php if($is_member && $loyaltyDetails['pointsSystem']['enabled']) { ?>
    <div class="diller-container coupons">
        <h2 class="page-title">
            <span class="base" data-ui-id="page-title-wrapper">Coupons</span>
        </h2>
        <hr>
        <?php echo $this->getLayout()->createBlock("Diller\LoyaltyProgram\Block\Frontend\Member")->setTemplate("Diller_LoyaltyProgram::coupons.phtml")->toHtml() ?>

    </div>
<?php } ?>
