<?php
    use Diller\LoyaltyProgram\Block\Frontend\Member;
    /** @var Member $block */

    $loyaltyHelper = $this->helper('Diller\LoyaltyProgram\Helper\Data');
    ?>
<?php
    if($block->getCustomer()){
        $customer_email = $block->getCustomer()->getEmail();
        $member = $block->getMemberByEmail($customer_email);
    }

    $loyaltyDetails = $loyaltyHelper->getLoyaltyDetails();
    $storeSegments = $loyaltyHelper->getStoreSegments();
    $storeDepartments = $loyaltyHelper->getStoreDepartments();
?>
<fieldset class="fieldset create account">
    <legend class="legend"><span><?= $loyaltyDetails['storeName'] ?></span></legend><br>
    <div class="field phonenumber required">
        <label class="label" for="phonenumber">
            <span><?= $block->escapeHtml(__('Phone Number')) ?></span>
        </label>
        <div class="control">
            <input type="text" name="loyalty_phone_countrycode" id="loyalty_phone_countrycode" value="<?= $member['phone']['countryCode'] ?? '' ?>">
            <input type="text" name="loyalty_phone_number" id="loyalty_phone_number" value="<?= $member['phone']['number'] ?? '' ?>" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" class="input-text" data-validate="{required:true}">
        </div>
    </div>

    <? if($block->getCustomer()){ ?>

        <!-- Birthdate -->
        <div class="loyalty field date">
            <label class="label" for="birthdate">
                <span><?= $block->escapeHtml(__('Birthdate')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="birth_date" id="birth_date" value="<?= isset($member['birthDate']) ? date_format($member['birthDate'],"d-m-Y") : '' ?>" title="<?= $block->escapeHtmlAttr(__('Birthdate')) ?>" class="input-date">
            </div>
        </div>

        <!-- Gender -->
        <?php
            $genders = array(
                array("id" => 1, "name" => "Male"),
                array("id" => 2, "name" => "Female"),
                array("id" => 4, "name" => "Non-binary"),
                array("id" => 3, "name" => "Don't want to share"),
            )
        ?>
        <div class="loyalty options field">
            <label class="label" for="gender">
                <span><?= $block->escapeHtml(__('Gender')) ?></span>
            </label>
            <div class="control">
                <?php foreach($genders as $gender ){?>
                    <div class="option">
                        <input type="radio" name="gender" id="<?= $gender['id'] ?>" value="<?= $gender['name'] ?>" title="<?= $gender['name'] ?>" class="input-radio" <?= !empty($member) ? (($member["gender"] === $gender['name']) ? 'checked' : '') : '' ?>>
                        <label for="<?= $gender['id'] ?>"><?= $gender['name'] ?></label>
                    </div>
                <?php } ?>
            </div>
        </div>

        <!-- Address -->
        <div class="loyalty field">
            <label class="label" for="address">
                <span><?= $block->escapeHtml(__('Address')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="address" id="address" value="<?= $member['address']['street'] ?? ''  ?>" title="<?= $block->escapeHtmlAttr(__('Address')) ?>" class="input-text">
            </div>
        </div>

        <!-- ZIPCODE -->
        <div class="loyalty field">
            <label class="label" for="zip_code">
                <span><?= $block->escapeHtml(__('Zip Code')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="zip_code" id="zip_code" value="<?= $member['address']['zipCode'] ?? ''  ?>" title="<?= $block->escapeHtmlAttr(__('Zip Code')) ?>" class="input-text">
            </div>
        </div>

        <!-- CITY -->
        <div class="loyalty field">
            <label class="label" for="city">
                <span><?= $block->escapeHtml(__('City')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="city" id="city" value="<?= $member['address']['city'] ?? ''  ?>" title="<?= $block->escapeHtmlAttr(__('City')) ?>" class="input-text">
            </div>
        </div>

        <!-- COUNTRY -->
        <div class="loyalty field">
            <label class="label" for="country_code">
                <span><?= $block->escapeHtml(__('Country')) ?></span>
            </label>
            <div class="control">
                <select name="country_code" id="country_code">
                    <option value="NO">Norway</option>
                    <option value="PT" <?= !empty($member) ? (($member['address']['countryCode'] == 'PT') ? 'selected' : '') : '' ?>>Portugal</option>
                </select>
            </div>
        </div>

        <!-- SEGMENTS -->
        <?php foreach($storeSegments as $segment ){
            if ($segment['isVisibleToFollower']) {

                $memberResponse = ['value' => '', 'selectedOptions' => []];
                if(!empty($member)){
                    foreach($member['segments'] as $segmentResponse){
                        if($segmentResponse['id'] == $segment['id']){
                            $memberResponse = $segmentResponse;
                            continue;
                        }
                    }
                }
                switch($segment['type']){
                    case ('DateTime'):
                        $segment_type = "date";
                        break;
                    case ('Dropdown'):
                        $segment_type = "select";
                        break;
                    case ('Radio'):
                        $segment_type = "radio";
                        break;
                    case ('Checkbox'):
                        $segment_type = "checkbox";
                        break;
                    default:
                        $segment_type = "text";
                } ?>
                <div class="loyalty <?= ($segment_type === 'radio' || $segment_type === 'checkbox') ? 'options' : ''?> field required">
                    <label class="label" for="segment_<?= $segment['id'] ?>">
                        <span><?= $segment['text'] ?></span>
                    </label>
                    <div class="control">
                        <?php if($segment_type === "select"){ ?>
                            <select name="segment_<?= $segment['id'] ?>" id="segment_<?= $segment['id'] ?>">
                                <option>...</option>
                                <?php foreach($segment['options'] as $option ){ ?>
                                    <option value="<?= $option['id'] ?>" <?= ($memberResponse['value'] == $option['id']) ? 'selected' : '' ?>><?= $option['text'] ?></option>
                                <?php } ?>
                            </select>
                        <?php }elseif($segment_type === "checkbox" || $segment_type === "radio"){
                            foreach($segment['options'] as $option ){ ?>
                                <div class="option">
                                    <input
                                        type="<?= $segment_type ?>"
                                        name="<?= ($segment_type === "checkbox") ? "segment_" . $segment['id']."[]" : "segment_" . $segment['id'] ?>"
                                        id="<?= $option['id'] ?>"
                                        value="<?= $option['id'] ?>"
                                        title="<?= $option['text'] ?>"
                                        class="input-<?= $segment_type ?>"
                                        data-validate="<?= $segment['isRequired'] ? '{required:true}' : '' ?>"
                                        <?php if((
                                                $segment_type === 'radio' &&
                                                $memberResponse['value'] == $option['id']
                                            ) || (
                                                $segment_type === 'checkbox' &&
                                                in_array($option['id'], $memberResponse['selectedOptions'])
                                            )){
                                                echo 'checked';
                                        } ?>
                                    >
                                    <label for="<?= $option['id'] ?>"><?= $option['text'] ?></label>
                                </div>
                            <?php }
                        }else{ ?>
                            <div class="control">
                                <input type="<?= $segment_type ?>" name="segment_<?= $segment['id'] ?>" id="segment_<?= $segment['id'] ?>" value="<?= $memberResponse['value'] ?? '' ?>" title="<?= $segment['id'] ?>" class="input-<?= $segment_type ?>">
                            </div>
                        <?php } ?>
                    </div>
                </div>
            <?php } ?>
        <?php } ?>

        <!-- DEPARTMENTS -->
        <?php if (!empty($storeDepartments)) { ?>
            <div class="loyalty options field required">
                <label class="label">
                    <span>Department</span>
                </label>
                <div class="control">
                    <?php foreach($storeDepartments as $option ){?>
                        <div class="option">
                            <input type="checkbox" name="department[]" id="<?= $option['id'] ?>" value="<?= $option['id'] ?>" title="<?= $option['name'] ?>" class="input-checkbox" data-validate="{required:true}" <?= !empty($member) ? (in_array($option['id'], $member['departmentIds']) ? 'checked' : '') : '' ?>>
                            <label for="<?= $option['id'] ?>"><?= $option['name'] ?></label>
                        </div>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    <?php } ?>

    <div class="loyalty options field">
        <label class="label">
            <span>Marketing Consent</span>
        </label>
        <div class="control">
            <div class="option">
                <input type="checkbox"
                       name="loyalty_consent"
                       id="loyalty_consent"
                       class="checkbox"
                    <?= !empty($member) ? ($member['consent']['gdprAccepted'] ? 'checked' : '') : '' ?>
                >
                <label for="loyalty_consent" class="label">
                    <span>I want to join <?= $loyaltyDetails['storeName'] ?>'s loyalty program and receive benefits, offers and other marketing communications electronically, including email, SMS and the like. Read our <a target="_blank" href="https://diller.app/<?= urlencode($loyaltyDetails["storeName"]) ?>/privacy-policy">privacy policy here</a></span>
                </label>
            </div>
            <div class="option">
                <input type="checkbox"
                       name="loyalty_consent_order_history"
                       id="loyalty_consent_order_history"
                       class="checkbox"
                    <?= !empty($member) ? ($member['consent']['saveOrderHistory'] ? 'checked' : '') : '' ?>
                >
                <label for="loyalty_consent_order_history" class="label">
                    <span> I want to get offers and benefits that suit me based on my preferences and purchase history.</span>
                </label>
            </div>
            <?php
                // TODO: wait for privacy policy url ON LOYALTY DETAILS
            ?>
        <?php if (!empty($member)){ ?>
                <div class="option">
                    <input type="checkbox"
                           name="loyalty_consent_sms"
                           id="loyalty_consent_sms"
                           class="checkbox"
                           <?= $member['consent']['receiveSms'] ? 'checked' : '' ?>
                    >
                    <label for="loyalty_consent_sms" class="label">
                        <span>SMS: I want to receive benefits, offers and other marketing electronically in connection with the customer club via SMS.</span>
                    </label>
                </div>
                <div class="option">
                    <input type="checkbox"
                           name="loyalty_consent_email"
                           id="loyalty_consent_email"
                           class="checkbox"
                            <?= $member['consent']['receiveEmail'] ? 'checked' : '' ?>
                    >
                    <label for="loyalty_consent_email" class="label">
                        <span>E-mail: I want to receive benefits, offers and other marketing electronically in connection with the customer club by E-mail.</span>
                    </label>
                </div>
        <?php } ?>
        </div>
    </div>
</fieldset>

<style>
    .field > .label{
        font-weight:bold;
    }
    .loyalty.field.options {
        float: left;
        width: 100%;
        display: block;
    }
    .loyalty.field.options > label {
        float: left;
        width: 100%;
    }
    .loyalty.field.options .control {
        margin-left: -5px;
        margin-right: -5px;
        float: left;
        width: 100%;
    }
    .loyalty.field.options .control > div {
        margin: 0 5px 5px;
        float: left;
    }
</style>
