<?php
    use Diller\LoyaltyProgram\Helper\Data;
    use Diller\LoyaltyProgram\Block\Frontend\Member;

    /** @var Member $block */
    /** @var \Magento\Framework\Escaper $escaper */

    /** @var Data $loyaltyHelper */
    $loyaltyHelper = $this->helper('Diller\LoyaltyProgram\Helper\Data');

    // member details
    $is_member = false;
    if($customer = $block->getCustomer()){
        $member = $loyaltyHelper->searchMemberByCustomerId($customer->getId());
        if($member){
            $is_member = $member->getConsent()->getGdprAccepted();
            if($customer->getCustomAttribute('diller_member_id') !== $member->getId()){
                $loyaltyHelper->addMemberIdToCustomer($customer->getId(), $member->getId());
            }
        }
    }

    // store details
    $loyaltyDetails = $loyaltyHelper->getLoyaltyDetails();
?>
<?php if($loyaltyDetails) { ?>
    <div class="loyalty-points">
        <?php if($is_member){
            if ($loyaltyDetails['pointsSystem']['enabled']) { ?>
                <p onclick="toLoyaltyProgramPage()" data-bind="text: new String('<?= $escaper->escapeHtml(__('You have %1 loyalty points!', '%1')) ?>').replace('%1', <?= $member['membershipDetail']['points'] ?>)"></p>
            <?php } else { ?>
                <p onclick="toLoyaltyProgramPage()"><?= $loyaltyDetails->getStoreName() ?></p>
            <?php } ?>
        <?php } else { ?>
            <p onclick="<?= empty($customer) ? 'toRegistrationPage()' : 'toUpdateAccountPage()'?>"><?= $escaper->escapeHtml(__('Join our Loyalty Program!')) ?></p>
        <?php } ?>
    </div>
    <script>
        function toLoyaltyProgramPage(){
            window.location.replace("/loyaltyprogram/customer/index/");
        }
        function toRegistrationPage(){
            window.location.replace("/customer/account/create/");
        }
        function toUpdateAccountPage(){
            window.location.replace("/customer/account/edit/");
        }
    </script>
    <style>
        .panel.header .loyalty-points {
            display: inline-block;
            margin-left: 15px;
            margin-right: 0;
            cursor: pointer;
            float: right;
        }
    </style>
<?php } ?>