<?php
use Diller\LoyaltyProgram\Block\Frontend\Member;
/** @var Member $block */
/** @var \Magento\Framework\Escaper $escaper */

$loyaltyHelper = $this->helper('Diller\LoyaltyProgram\Helper\Data');

// member details
$is_member = false;
if($customer = $block->getCustomer()){
    $is_member = ($member = $loyaltyHelper->searchMemberByCustomerId($customer->getId()));
}

// store details
$loyaltyDetails = $loyaltyHelper->getLoyaltyDetails();
?>

<?php if ($is_member && $loyaltyDetails['pointsSystem']['enabled']) : ?>
    <div class="loyalty-points">
        <p onclick="toLoyaltyProgramPage()" data-bind="text: new String('<?= $escaper->escapeHtml(__('You have %1 loyalty points!', '%1')) ?>').replace('%1', <?= $member['membershipDetail']['points'] ?>)">
        </p>
    </div>
    <script>
        function toLoyaltyProgramPage(){
            window.location.replace("/loyaltyprogram/customer/index/");
        }
    </script>
    <style>
        .panel.header .loyalty-points {
            display: inline-block;
            margin-left: 15px;
            margin-right: 0;
            cursor: pointer;
            float: right;
        }
    </style>
<?php endif ?>
