<?php
    /** @var Member $block */
    use Diller\LoyaltyProgram\Block\Frontend\Member;

    /** @var $escaper \Magento\Framework\Escaper */

    $loyaltyHelper = $this->helper('Diller\LoyaltyProgram\Helper\Data');

    // member details
    $is_member = false;
    if($customer = $block->getCustomer()){
        $member = $loyaltyHelper->searchMemberByCustomerId($customer->getId());
        if($member){
            $is_member = $member->getConsent()->getGdprAccepted();
        }
        if($is_member){
            $gender = $member->getGender();
            switch ($member->getGender()) {
                case "NotShared":
                    $gender = $escaper->escapeHtml(__("Don't want to share"));
                    break;
                case "NonBinary":
                    $gender = $escaper->escapeHtml(__("Non binary"));
                    break;
                default:
                    $gender = $member->getGender();
            }
        }
    }

    // store details
    $loyaltyDetails = $loyaltyHelper->getLoyaltyDetails();
?>

<?php if(!$is_member) {
    echo sprintf($escaper->escapeHtml(__("To enroll to our Loyalty program <strong>%s</strong> and enjoy the benefits, please <a href='/customer/account/edit/'>click here</a>"), ['a', 'strong']), $loyaltyDetails['storeName']);
}else{ ?>
    <div class="diller-container member-info id_<?= $member->getId() ?>">
        <h2 class="page-title">
            <span class="base" data-ui-id="page-title-wrapper"><?= $escaper->escapeHtml(__('Personal details')) ?></span>
        </h2>
        <hr>
        <div>
            <ul>
                <li><strong><?= $escaper->escapeHtml(__('Name')) ?></strong> <?= $member->getFirstName() ?> <?= $member->getLastName() ?></li>
                <li><strong><?= $escaper->escapeHtml(__('Phone number')) ?></strong> <?= $member->getPhone()->getCountryCode() ?> <?= $member->getPhone()->getNumber() ?></li>
                <li><strong><?= $escaper->escapeHtml(__('Email')) ?></strong> <?= $member->getEmail() ?></li>
                <li><strong><?= $escaper->escapeHtml(__('Gender')) ?></strong> <?= $gender ?? '' ?></li>
                <li><strong><?= $escaper->escapeHtml(__('Address')) ?></strong> <?= $member->getAddress()->getStreet() ?><br><?= $member->getAddress()->getZipCode() ?> <?= $member->getAddress()->getCity() ?> - <?= $member->getAddress()->getCountryCode() ?></li>
                <li><strong><?= $escaper->escapeHtml(__('Birthdate')) ?></strong> <?= ($member->getBirthDate() != null) ? date_format($member->getBirthDate(),"d-m-Y") : 'N/A' ?></li>
                <li><strong><?= $escaper->escapeHtml(__('Marketing consent')) ?></strong>
                    <ul>
                        <li>
                            <strong><?= $escaper->escapeHtml(__('Sms')) ?></strong> <?= $member->getConsent()->getReceiveSms() ? $escaper->escapeHtml(__('Yes')) : $escaper->escapeHtml(__('No')) ?><br>
                            <strong><?= $escaper->escapeHtml(__('Email')) ?></strong> <?= $member->getConsent()->getReceiveEmail() ? $escaper->escapeHtml(__('Yes')) : $escaper->escapeHtml(__('No')) ?><br>
                            <strong><?= $escaper->escapeHtml(__('Order history consent')) ?></strong> <?= $member->getConsent()->getSaveOrderHistory() ? $escaper->escapeHtml(__('Yes')) : $escaper->escapeHtml(__('No')) ?><br>
                            <strong><?= $escaper->escapeHtml(__('GDPR accepted')) ?></strong> <?= $member->getConsent()->getGDPRAccepted() ? $escaper->escapeHtml(__('Yes')) : $escaper->escapeHtml(__('No')) ?>
                        </li>
                    </ul>
                </li>
                <li class="button"><button id="edit"><?= $escaper->escapeHtml(__('Edit personal details')) ?></button></li>
            </ul>
        </div>
    </div>

    <script>
        document.querySelector(".member-info button#edit").onclick = function() {
            window.location.href = "/customer/account/edit/";
        }
    </script>

    <style id="diller-store-styles-inline-css">
        :root {
            --diller-buttons-background-color: #90b3c7;
            --diller-buttons-background-color-hover: #a7c3d3;
            --diller-membership_progress_bar-background-color: #90b3c7;
        }
    </style>

    <style>
        .diller-container ul {
            list-style: none;
            padding: 0;
        }
        .diller-container div > ul {
            float: left;
            width: 100%;
            columns: 2;
            -webkit-columns: 2;
            -moz-columns: 2;
            margin:0;
        }
        .diller-container div > ul > li {
            width: 100%;
            float: left;
        }
        .diller-container ul li ul {
            margin: 5px 0;
            float: left;
            width: 100%;
        }
        .diller-container ul li ul li:only-child {
            margin: 0 !important;
        }

        .diller-container li.button {
            padding: 10px 0;
        }
    </style>
<?php } ?>