<?php
    use Diller\LoyaltyProgram\Block\Frontend\Member;
    /** @var Member $block */

    $loyaltyHelper = $this->helper('Diller\LoyaltyProgram\Helper\Data');
?>
<?php
    if($block->getCustomer()){
        $customer_email = $block->getCustomer()->getEmail();
        $member = $block->getMemberByEmail($customer_email);
    }
    $loyaltyDetails = $loyaltyHelper->getLoyaltyDetails();
?>

<?php if(empty($member)) { ?>
    To enroll to our Loyalty program "<b><?= $loyaltyDetails['storeName'] ?></b>" and enjoy the benefits, please <a href="/customer/account/edit/">click here</a>
<?php }else{ ?>
    <div class="diller-container member-info id_<?= $member['id'] ?>">
        <h2 class="page-title">
            <span class="base" data-ui-id="page-title-wrapper">Personal details</span>
        </h2>
        <hr>
        <div>
            <ul>
                <li><strong>Name</strong> <?= $member['firstName'] ?> <?= $member['lastName'] ?></li>
                <li><strong>Phone number</strong> <?= $member['phone']['countryCode'] ?> <?= $member['phone']['number'] ?></li>
                <li><strong>Email</strong> <?= $member['email'] ?></li>
                <li><strong>Gender</strong> <?= $member['gender'] ?></li>
                <li><strong>Address</strong> <?= $member['address']['street'] ?><br><?= $member['address']['zipCode'] ?> <?= $member['address']['city'] ?> - <?= $member['address']['countryCode'] ?>
                </li>
                <li><strong>Birthdate</strong> <?= isset($member['birthDate']) ? date_format($member['birthDate'],"d-m-Y") : 'N/A' ?></li>
                <li><strong>Communications consent</strong>
                    <ul>
                        <li>
                            <strong>Sms</strong> <?= $member['consent']['receiveSms'] ? 'Yes' : "No" ?><br>
                            <strong>Email</strong> <?= $member['consent']['receiveEmail'] ? 'Yes' : "No" ?>
                        </li>
                    </ul>
                </li>
                <li><strong>GDPR accepted</strong> <?= $member['consent']['gdpr_accepted'] ? 'Yes' : "No" ?></li>
                <li><strong>Order history consent</strong> <?= $member['consent']['saveOrderHistory'] ? 'Yes' : "No" ?></li>
                <li class="button"><button id="edit">Edit personal details</button></li>
            </ul>
        </div>
    </div>

    <script>
        document.querySelector(".member-info button#edit").onclick = function() {
            window.location.href = "/customer/account/edit/";
        }
    </script>

    <style id="diller-store-styles-inline-css">
        :root {
            --diller-buttons-background-color: #90b3c7;
            --diller-buttons-background-color-hover: #a7c3d3;
            --diller-membership_progress_bar-background-color: #90b3c7;
        }
    </style>

    <style>
        .diller-container ul {
            list-style: none;
            padding: 0;
        }
        .diller-container div > ul {
            float: left;
            width: 100%;
            columns: 2;
            -webkit-columns: 2;
            -moz-columns: 2;
            margin:0;
        }
        .diller-container div > ul > li {
            width: 100%;
            float: left;
        }
        .diller-container ul li ul {
            margin: 5px 0;
            float: left;
            width: 100%;
        }
        .diller-container ul li ul li:only-child {
            margin: 0 !important;
        }

        .diller-container li.button {
            padding: 10px 0;
        }
    </style>
<?php } ?>
