<?php
    /** @var Member $block */
    use Diller\LoyaltyProgram\Block\Frontend\Member;

    $loyaltyHelper = $this->helper('Diller\LoyaltyProgram\Helper\Data');

    // member details
    $is_member = false;
    if($customer = $block->getCustomer()){
        $is_member = ($member = $loyaltyHelper->searchMemberByCustomerId($customer->getId()));
        if($is_member){
            $coupons = $block->getMemberCoupons($member['id']);
            $gender = $member->getGender();
            switch ($member->getGender()) {
                case "NotShared":
                    $gender = "Don't want to share";
                    break;
                case "NonBinary":
                    $gender = "Non binary";
                    break;
                default:
                    $gender = $member->getGender();
            }
        }
    }

    // store details
    $loyaltyDetails = $loyaltyHelper->getLoyaltyDetails();
?>

<?php if(!$is_member) { ?>
    To enroll to our Loyalty program "<b><?= $loyaltyDetails['storeName'] ?></b>" and enjoy the benefits, please <a href="/customer/account/edit/">click here</a>
<?php }else{ ?>
    <div class="diller-container member-info id_<?= $member->getId() ?>">
        <h2 class="page-title">
            <span class="base" data-ui-id="page-title-wrapper">Personal details</span>
        </h2>
        <hr>
        <div>
            <ul>
                <li><strong>Name</strong> <?= $member->getFirstName() ?> <?= $member->getLastName() ?></li>
                <li><strong>Phone number</strong> <?= $member->getPhone()->getCountryCode() ?> <?= $member->getPhone()->getNumber() ?></li>
                <li><strong>Email</strong> <?= $member->getEmail() ?></li>
                <li><strong>Gender</strong> <?= $gender ?? '' ?></li>
                <li><strong>Address</strong> <?= $member->getAddress()->getStreet() ?><br><?= $member->getAddress()->getZipCode() ?> <?= $member->getAddress()->getCity() ?> - <?= $member->getAddress()->getCountryCode() ?>
                </li>
                <li><strong>Birthdate</strong> <?= ($member->getBirthDate() != null) ? date_format($member->getBirthDate(),"d-m-Y") : 'N/A' ?></li>
                <li><strong>Communications consent</strong>
                    <ul>
                        <li>
                            <strong>Sms</strong> <?= $member->getConsent()->getReceiveSms() ? 'Yes' : "No" ?><br>
                            <strong>Email</strong> <?= $member->getConsent()->getReceiveEmail() ? 'Yes' : "No" ?>
                        </li>
                    </ul>
                </li>
                <li><strong>GDPR accepted</strong> <?= $member->getConsent()->getGDPRAccepted() ? 'Yes' : "No" ?></li>
                <li><strong>Order history consent</strong> <?= $member->getConsent()->getSaveOrderHistory() ? 'Yes' : "No" ?></li>
                <li class="button"><button id="edit">Edit personal details</button></li>
            </ul>
        </div>
    </div>

    <script>
        document.querySelector(".member-info button#edit").onclick = function() {
            window.location.href = "/customer/account/edit/";
        }
    </script>

    <style id="diller-store-styles-inline-css">
        :root {
            --diller-buttons-background-color: #90b3c7;
            --diller-buttons-background-color-hover: #a7c3d3;
            --diller-membership_progress_bar-background-color: #90b3c7;
        }
    </style>

    <style>
        .diller-container ul {
            list-style: none;
            padding: 0;
        }
        .diller-container div > ul {
            float: left;
            width: 100%;
            columns: 2;
            -webkit-columns: 2;
            -moz-columns: 2;
            margin:0;
        }
        .diller-container div > ul > li {
            width: 100%;
            float: left;
        }
        .diller-container ul li ul {
            margin: 5px 0;
            float: left;
            width: 100%;
        }
        .diller-container ul li ul li:only-child {
            margin: 0 !important;
        }

        .diller-container li.button {
            padding: 10px 0;
        }
    </style>
<?php } ?>
