<?php
use Diller\LoyaltyProgram\Block\Frontend\Member;
/** @var Member $block */
?>
<?php
    if($block->getCustomer()){
        $customer_email = $block->getCustomer()->getEmail();
        $member = $block->getMember($customer_email)[0];
    }
    $loyaltyDetails = $block->getLoyaltyDetails();
?>
<?php if(!empty($member) && $loyaltyDetails['pointsSystem']['enabled']) { ?>
    <div class="diller-container points">
        <h2 class="page-title">
            <span class="base" data-ui-id="page-title-wrapper">Points</span>
        </h2>
        <hr>
        <div>
            <span class="">My level: <span><b><?= $member['membershipDetail']['levelTitle'] ?></b></span></span>
            <br>
            <span>
                Points for use:
                <span>
                    <b><?= $member['membershipDetail']['points'] ?> points</b>
                    <small></small>
                </span>
            </span>
            <br>
            <span>
                Points till next level (<?= $member['membershipDetail']['nextLevelTitle'] ?>):
                <span><b><?= $member['membershipDetail']['nextLevelPoints'] ?> points</b></span>
            </span>
        </div>

        <div class="diller-membership-progress" style="margin: 25px 0;">
            <div class="diller-membership-progress-points">
                <?php //foreach($loyaltyDetails['membership_levels'] as $level){ ?>
                    <div><?= 'points' //$level['points'] ?></div>
                <?php //} ?>
            </div>
            <div class="diller-membership-progress-bar">
                <div class="diller-membership-progress-bar-indicator" style="width:25%;"></div>
            </div>
            <div class="diller-membership-progress-points">
                <?php //foreach($loyaltyDetails['membership_levels'] as $level){ ?>
                    <div><?= 'title' //= $level['title'] ?></div>
                <?php //} ?>
            </div>
        </div>
    </div>

    <style>
        .diller-container{
            margin: 0 0 50px;
            position: relative;
            float: left;
            width: 100%;
        }

        /* Points progressbar */
        .diller-membership-progress {
            display: flex;
            flex-direction: column;
        }

        .diller-membership-progress-points > div, .diller-membership-progress-labels > div {
            position: absolute;
        }

        .diller-membership-progress-points > div:last-child, .diller-membership-progress-points > div:last-child, .diller-membership-progress-labels > div:last-child, .diller-membership-progress-labels > div:last-child {
            transform: translate(-100%);
        }

        .diller-membership-progress-bar {
            color: #000;
            background-color: #fff;
            border-radius: 50px;
            padding: 5px;
            width: 100%;
        }

        .diller-membership-progress-bar-indicator {
            height: 24px;
            color: #000;
            border-radius: 50px;
            padding: 20px;
            background-color: var(--diller-membership_progress_bar-background-color);
            width: 0;
        }

        .diller-box .diller-membership-progress-points, .diller-box .diller-membership-progress-labels {
            position: relative;
            height: 50px;
        }

        .diller-heading__title {
            margin: 0 0 30px 0;
            font-size: 2.5rem;
        }

        .diller-heading__subtitle {
            margin: 30px 0;
            font-size: 1.5rem;
        }

        .diller-invitation-list {
            margin: 60px 0 30px 0;
        }
    </style>
<?php } ?>
