<?php
/** @var Member $block */
use Diller\LoyaltyProgram\Block\Frontend\Member;

$loyaltyHelper = $this->helper('Diller\LoyaltyProgram\Helper\Data');

// member details
$is_member = false;
if($customer = $block->getCustomer()){
    $valid_stamp_cards = $stamp_cards = [];
    $member = $loyaltyHelper->searchMemberByCustomerId($customer->getId());
    if($member){
        $is_member = $member->getConsent()->getGdprAccepted();
    }
    if($is_member && $stamp_cards = $block->getMemberStampCards($member['id'])){
        foreach ($stamp_cards as $stamp_card) {
            $price_rule = $loyaltyHelper->getPriceRule($stamp_card->getExternalId(), "Stamp Card - " . $stamp_card->getTitle());
            if(!$price_rule) continue;

            $stamp_card_products = [];
            foreach ($price_rule->getActionCondition()->getConditions() as $price_rule_conditions){
                foreach(explode(',', $price_rule_conditions->getValue()) as $product_sku){
                    if($product_found = $loyaltyHelper->getMagentoProduct('', $product_sku)){
                        $stamp_card_products[] = $product_found;
                    }
                }
            }
            $stamp_card['products'] = $stamp_card_products;
            if(!empty($stamp_card_products)) $valid_stamp_cards[] = $stamp_card;
        }
    }
}

// store details
$loyaltyDetails = $loyaltyHelper->getLoyaltyDetails();
?>
<?php if($is_member && !empty($valid_stamp_cards)) { ?>
    <div class="diller-container stamp-cards">
        <h3 class="page-title">
            <span id="diller-stamp-cards-container-title-cart" style="display:none" class="base" data-ui-id="page-title-wrapper"><b><?= $loyaltyDetails['storeName'] ?></b> stamp cards</span>
            <span id="diller-stamp-cards-container-title-loyalty-page" class="base" data-ui-id="page-title-wrapper">Stamp Cards</span>
        </h3>
        <hr>


        <?php
            foreach ($valid_stamp_cards as $stamp_card) { ?>
            <div class="stamp-card id_<?= $stamp_card->getId() ?>">
                <h3><?= $stamp_card->getTitle() ?></h3>
                <p><?= $stamp_card->getDescription() ?> (<?=$stamp_card->getStampsCollected() ?>/<?=$stamp_card->getRequiredStamps() ?>)</p>
                <div class="stamps">
                    <?php for ($x = 1; $x <= $stamp_card->getRequiredStamps(); $x++) { ?>
                        <div class="stamp <?= $stamp_card->getStampsCollected() >= $x ? 'collected' : '' ?>" <?= $x == $stamp_card->getRequiredStamps() ? 'title="'.$stamp_card->getLastStampText().'"' : '' ?>></div>
                    <?php } ?>
                </div>
                <div class="products">
                    <?= "<p>To add a new stamp to this card, you must buy " . (count($stamp_card['products']) > 1 ? "one of following products" : "the following product") . '</p>' ?>
                    <ul>
                        <?php foreach($stamp_card['products'] as $product){ ?>
                            <li><a href="<?= $product->getProductUrl() ?>" target="_blank"><?= $product->getName() ?></a></li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
            <style>
                .stamp-cards .id_<?= $stamp_card->getId() ?> .stamp{
                    background-image: url("<?= $stamp_card->getImageUrl() ?>") !important;
                }
            </style>
        <?php } ?>
    </div>
    <style>
        body.checkout-cart-index span#diller-stamp-cards-container-title-cart{
            display: block !important;
        }
        body.checkout-cart-index #diller-stamp-cards-container-title-loyalty-page{
            display: none;
        }
        .diller-container.stamp-cards{
            float:left;
            width: 100%;
        }

        .stamp-card {
            margin: 0 0 40px;
            float: left;
            width: 100%;
        }
        .stamp-card h3 {
            text-transform: capitalize;
            margin: 0 0 5px;
        }
        .stamp-card p {
            margin: 0 0 15px;
        }
        .stamp-card .stamps {
            display: flex;
            gap: 10px;
        }
        .stamp-card .stamps .price{
            justify-content: center;
            align-items: center;
            width: min-content;
            font-weight: 600;
            min-width: 80px;
            display: flex;
        }
        .stamp-card .stamps .stamp {
            background-position: center center;
            background-repeat: no-repeat;
            border: 3px solid #f5f5f5;
            background-color: #fff;
            background-size: 60%;
            border-radius: 100%;
            display: flex;
            height: 60px;
            opacity: 0.5;
            width: 60px;
        }
        .stamp-card .stamps .stamp.collected {
            border-color: #90b3c7;
            opacity: 1;
        }
        .stamp-card .products{
            margin:20px 0 0 0;
        }
        .stamp-card .products ul{
            list-style: initial;
            padding: 0 0 0 30px;
            display: inline-grid;
            margin:0;
        }
        .stamp-card .products ul li{
            margin: 0 0 5px;
        }
    </style>
<?php } ?>
